title: Sai Satwik Kuppili
logo: /assets/img/profilepic.jpg
description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/saisatwikkuppili/">LinkedIn</a> |
  <a href="https://scholar.google.co.in/citations?user=s3nuoYgAAAAJ&hl=en&oi=ao">Google Scholar</a> |
  <a href="https://orcid.org/0000-0002-0280-127X">ORCiD</a> |
#   <a href="https://github.com/SaiSatwik">GitHub</a>
  </p>
  
  <p align="left">
  I'm working on Global Search, Machine Learning and NLP realated problems. Has published algorithmic research articles. </br>
  Working with NSXT Search team at VMware R&D.</br>
  Pursuing Post Graduation Diploma in Machine Learning & AI from IIIT Bangalore. </br>
  Serving as a TPC member for 3ICT2021. Served as a reviewer on the editorial committee for IJCDS-2020. </br>
  Graduated with a Gold medal, B.Tech at Amrita University.
  </p>
theme: jekyll-theme-minimal
